steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ssfs-202408/ssfs-ethan-oct16:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ssfs-202408/ssfs-ethan-oct16:$SHORT_SHA']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ssfs-ethan-oct16'
      - '--image'
      - 'gcr.io/ssfs-202408/ssfs-ethan-oct16:$SHORT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/ssfs-202408/ssfs-ethan-oct16:$SHORT_SHA'